import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Foot from "./components/Foot";
import { FavoritosProvider } from "@/app/context/FavContext.js";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Snippetia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <Nav />
        <FavoritosProvider>{children}</FavoritosProvider>
        <Foot />
      </body>
    </html>
  );
}
